// A static, version-stamped catalog of the tools this server registers, joined
// with their route-to-capability rows. Generated by `npm run catalog:export` into
// catalog/tools-catalog.json (committed); a drift test asserts the committed file
// matches a fresh build, so a newly registered tool or an edited description that
// was not re-exported fails CI. A copy of the JSON is rendered by the Mission
// Control MCP tab's Tools section (so an operator sees what an AI client can do).

import { ToolRegistry } from "../registry/tools.js";
import { registerReadTools } from "../registry/read-tools.js";
import { registerAdminTools } from "../registry/admin-tools.js";
import { routeCapFor } from "../auth/route-capability.js";
import { SERVER_VERSION, MCP_SPEC_REVISION } from "../version.js";
import type { SafetyClass, ScopeGroup } from "../auth/scopes.js";

export interface CatalogTool {
  name: string;
  group: string;
  scope: ScopeGroup;
  safetyClass: SafetyClass;
  description: string;
  agentModeOnly?: boolean;
  affectsFlight?: boolean;
}

export interface ToolsCatalog {
  version: string;
  mcpRevision: string;
  toolCount: number;
  tools: CatalogTool[];
}

/**
 * Build the catalog from a fresh registry (read + admin tools) joined to the
 * route-capability table. Driving from the REGISTRY (not the 71-row table) is
 * what makes the drift test catch a missing entry: `ToolRegistry.register` throws
 * if a tool has no route row, so every registered tool is guaranteed a row to
 * join, and a newly-registered tool appears in a fresh build but not the committed
 * file until re-exported. The audit path is irrelevant to the catalog, so a
 * placeholder is fine.
 */
export function buildToolsCatalog(): ToolsCatalog {
  const reg = new ToolRegistry();
  registerReadTools(reg, "/dev/null");
  registerAdminTools(reg);

  const tools: CatalogTool[] = reg
    .all()
    .map((def): CatalogTool => {
      const cap = routeCapFor(def.name);
      if (!cap) throw new Error(`no route-capability row for registered tool ${def.name}`);
      return {
        name: def.name,
        group: def.name.split(".")[0] ?? def.name,
        scope: cap.scope,
        safetyClass: cap.safetyClass,
        description: def.description,
        ...(cap.agentModeOnly ? { agentModeOnly: true } : {}),
        ...(cap.affectsFlight ? { affectsFlight: true } : {}),
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name));

  return {
    version: SERVER_VERSION,
    mcpRevision: MCP_SPEC_REVISION,
    toolCount: tools.length,
    tools,
  };
}

/** The stable JSON serialization used for both the committed file and the drift test. */
export function serializeCatalog(catalog: ToolsCatalog): string {
  return JSON.stringify(catalog, null, 2) + "\n";
}
